### ISSUE TITLE
 PWM frequency

### ISSUE THREAD

**Issue by StevenAMC** [danjperron/Pi5PWM_HARDWARE#2]
How do I select the PWM frequency, please?

**Comment by danjperron** [comment]
The PWM clock on the PI5 is not documented but I was able to reverse engineer  and I found that the base clock is around 30MHz.

The frequency of the PWM is set by the range.

ex: On my code  you will see that the  total frequency is 50Hz and the default ON pulse rate is 1.5ms which is the center of any R/C servo

Frequency for R/C servo is 50Hz (20ms) then  range = 30303030 (30Mhz) / 50 = 606060 (I know on my code is 615318)
 pwm0[PWM_CHANNEL[currentPWM]+PWM_CHAN_RANGE]= 615318; // it should be 606060

Duty for 1.5ms On    duty=30303030  *1.5e-3 = 45454.5 => 45455 (NOt sure if I need to remove 1)
    pwm0[PWM_CHANNEL[currentPWM]+PWM_CHAN_DUTY]= 45455;
